remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true
syntax_highlighter_style: colorful

collections:
  pages:
    output: true
    label: Getting Started!
    permalink: /:collection/:path/
  developers:
    output: true
    label: 開発者向け
    permalink: /:collection/:path/
  fhir:
    output: true
    label: FHIR
    permalink: /:collection/:path/
  analytics:
    output: true
    label: analytics
    permalink: /:collection/:path/
  containers:
    output: true
    label: コンテナ
    permalink: /:collection/:path/
  administrators:
    output: true
    label: 管理者向け
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/


ordered_collections:
  - posts
  - developers
  - fhir
  - analytics
  - containers
  - administrators
  - others

favicon_path: ./assets/icons/favicon.ico
