title: InterSystems Learning Path
description: >
  InterSystems製品を学習するためのパスをペルソナ別でご紹介しています。
remote_theme: sighingnow/jekyll-gitbook

toc:
    enabled: true
    h_max: 2
syntax_highlighter_style: colorful

tracker:
  google_analytics: G-1LQVED30HC

collections:
  pages:
    output: true
    label: Getting Started!
    permalink: /:collection/:path/
  developers:
    output: true
    label: 開発者向け
    permalink: /:collection/:path/
  fhir:
    output: true
    label: FHIR
    permalink: /:collection/:path/
  genai:
    output: true
    label: GENAI
    permalink: /:collection/:path/
  analytics:
    output: true
    label: analytics
    permalink: /:collection/:path/
  containers:
    output: true
    label: コンテナ
    permalink: /:collection/:path/
  administrators:
    output: true
    label: 管理者向け
    permalink: /:collection/:path/


ordered_collections:
  - posts
  - developers
  - fhir
  - genai
  - analytics
  - containers
  - administrators

favicon_path: ./assets/icons/favicon.ico
