repository: iijimam/LPTest
remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true
syntax_highlighter_style: colorful

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  developers:
    output: true
    permalink: /:collection/:path/
  sysmgts:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/


ordered_collections:
  - posts
  - developers
  - sysmgts
  - others

favicon_path: ./assets/icons/favicon.ico
